apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcc-sql-composition
spec:
  compositeTypeRef:
    apiVersion: infra.sample.org/v1alpha1
    kind: XSQLResource
  resources:
  - name: managedkccsqlinstance
    base:
      apiVersion: sql.cnrm.cloud.google.com/v1beta1
      kind: SQLInstance
      metadata:
        labels:
          label-one: "kcc-composite"
        namespace: "config-control"
      spec:
        databaseVersion: MYSQL_5_7
        region: us-central1
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.size
      toFieldPath: spec.settings.tier
      transforms:
      - type: map
        map:
          large: "db-n1-standard-64"
          medium: "db-n1-standard-4"
          small: "db-f1-micro"
